arxiu:
    pattern: /
    defaults:
        _controller: ArxiuBundle:Default:arxiu
        
guia_routes:
    resource: "@ArxiuBundle/Resources/config/routing/guia.yml"
    prefix:   /guia      
    
fons_routes:
    resource: "@ArxiuBundle/Resources/config/routing/fons.yml"
    prefix:   /fons                      
        
dispenses_routes:
    resource: "@ArxiuBundle/Resources/config/routing/dispenses.yml"
    prefix:   /dispenses
    
llistat_routes:
    resource: "@ArxiuBundle/Resources/config/routing/llistat.yml"
    prefix:   /llistat        
               
documents_routes:
    resource: "@ArxiuBundle/Resources/config/routing/documents.yml"
    prefix:   /documents

parroquies_routes:
    resource: "@ArxiuBundle/Resources/config/routing/parroquies.yml"
    prefix:   /parroquies

guia_antiga_routes:
    resource: "@ArxiuBundle/Resources/config/routing/guiaAntiga.yml"
    prefix:   /guia/antiga