arrel:
    pattern: /
    defaults:
        _controller:  PrincipalBundle:Default:index 

arxiu:
    resource: "@ArxiuBundle/Resources/config/routing.yml"
    prefix:   /arxiu

principal:
    resource: "@PrincipalBundle/Resources/config/routing.yml"
    prefix:   /
    pattern:  

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


