arrel:
    pattern: /
    defaults:
        _controller:  PrincipalBundle:Default:index 

arxiu:
    resource: "@ArxiuBundle/Resources/config/routing.yml"
    prefix:   /

principal:
    resource: "@PrincipalBundle/Resources/config/routing.yml"
    prefix:   /
    pattern:  


