jms_security_extra:
    secure_all_services: false
    expressions: true
    
security:
    encoders:
        ADG\PrincipalBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
       users:
            entity: { class: Adg\PrincipalBundle\Entity\User }
            
    firewalls:
        login:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: index
                always_use_default_target_path: true
            remember_me:
                key: ADG
                lifetime: 31536000
            logout:
                path: logout
                target: index
     
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/normativa, roles: ROLE_USER }
        

        
        
        
