documents:
    pattern: /
    defaults:
        _controller: ArxiuBundle:Documents:documents

documents_select:
    pattern: /{seleccio}
    defaults:
        _controller: ArxiuBundle:Documents:select
        
documents_cercar:
    pattern: /cercar/{seleccio}
    defaults:
        _controller: ArxiuBundle:Documents:cercar
    requirements: { _method: post }

documents_cercarAdlimina:
    pattern: /cercar/adlimina/{seleccio}
    defaults:
        _controller: ArxiuBundle:Documents:cercarAdlimina
    requirements: { _method: post }    
    
documents_detall:
    pattern: /detall/{id}
    defaults:
        _controller: ArxiuBundle:Documents:detall
