index:
    pattern:  /index
    defaults: 
        _controller: PrincipalBundle:Default:index

contacte:
    pattern: /contacte
    defaults:
        _controller: PrincipalBundle:Default:contacte
        
normativa:
    pattern: /normativa
    defaults:
        _controller: PrincipalBundle:Default:normativa
        
capitular:
    pattern: /capitular
    defaults:
        _controller: PrincipalBundle:Default:capitular

info_web:
    pattern: /web
    defaults:
        _controller: PrincipalBundle:Default:web  
        
admin_routes:
    resource: "@PrincipalBundle/Resources/config/routing/admin.yml"
    prefix:   /admin            
