admin:
    pattern: /dashboard
    defaults:
        _controller: PrincipalBundle:Admin:admin
        
noticies:
    pattern: /noticies/
    defaults:
        _controller: PrincipalBundle:Admin:noticies