parameters:
#    principal.example.class: ADG\PrincipalBundle\Example

services:
    adg.bibliotecabundle.menu.voter.request:
        class: ADG\PrincipalBundle\Menu\RequestVoter
        arguments:
            - "@service_container"
        tags:
            - name: knp_menu.voter