admin:
    pattern: /general
    defaults:
        _controller: PrincipalBundle:Admin:admin
                   
noticies:
    resource: "@PrincipalBundle/Resources/config/routing/noticies.yml"
    prefix:   /noticies
    
admin_guia:
    resource: "@PrincipalBundle/Resources/config/routing/guia.yml"
    prefix:   /guia                      
        