admin:
    pattern: /general
    defaults:
        _controller: PrincipalBundle:Admin:admin
                   
noticies:
    resource: "@PrincipalBundle/Resources/config/routing/noticies.yml"
    prefix:   /noticies
    
admin_guia:
    resource: "@PrincipalBundle/Resources/config/routing/guia.yml"
    prefix:   /guia
    
admin_users:
    resource: "@PrincipalBundle/Resources/config/routing/users.yml"
    prefix:   /usuaris                          
        