fons_nou:
    pattern:  /nou
    defaults: { _controller: "PrincipalBundle:AdminFons:nou" }
    
fons_nou_confirmar:
    pattern:  /confirmar/nou
    defaults: { _controller: "PrincipalBundle:AdminFons:nouConfirmar" }
    requirements: { _method: post }
    
fons_editar:
    pattern:  /{id}/editar
    defaults: { _controller: "PrincipalBundle:AdminFons:editar" }
    
fons_editar_confirmar:
    pattern:  /editar/confirmar
    defaults: { _controller: "PrincipalBundle:AdminFons:editarConfirmar" }
    requirements: { _method: post }    
    
fons_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "PrincipalBundle:AdminFons:eliminar" }    

fons_eliminar_confirmar:
    pattern:  /eliminar/confirmar
    defaults: { _controller: "PrincipalBundle:AdminFons:eliminarConfirmar" }
    requirements: { _method: post }    
    
    