guia_nou:
    pattern:  /nou/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:nou" }
    
guia_nou_confirmar:
    pattern:  /confirmar/nou
    defaults: { _controller: "PrincipalBundle:AdminGuia:nouConfirmar" }
    requirements: { _method: post }           

guia_subnivell:
    pattern:  /subnivell/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:subnivell" }
    
guia_subnivell_confirmar:
    pattern:  /confirmar/subnivell
    defaults: { _controller: "PrincipalBundle:AdminGuia:subnivellConfirmar" }
    requirements: { _method: post }        

guia_editar:
    pattern:  /editar/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:editar" }
    
guia_editar_confirmar:
    pattern:  /confirmar/editar
    defaults: { _controller: "PrincipalBundle:AdminGuia:editarConfirmar" }
    requirements: { _method: post }
    
guia_tots:
    pattern:  /tots/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:tots" }
    
guia_tots_confirmar:
    pattern:  /confirmar/tots
    defaults: { _controller: "PrincipalBundle:AdminGuia:totsConfirmar" }
    requirements: { _method: post }        
            
guia_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "PrincipalBundle:AdminGuia:eliminar" }
    
guia_eliminar_confirmar:
    pattern:  /eliminar/confirmar
    defaults: { _controller: "PrincipalBundle:AdminGuia:eliminarConfirmar" }
    requirements: { _method: post }            
