guia_nou:
    pattern:  /nou/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:nou" }
    
guia_nou_confirmar:
    pattern:  /nou/confirmar
    defaults: { _controller: "PrincipalBundle:AdminGuia:nouConfirmar" }
    requirements: { _method: post }           

guia_subnivell:
    pattern:  /subnivell/{id}
    defaults: { _controller: "PrincipalBundle:AdminGuia:subnivell" }
    
guia_subnivell_confirmar:
    pattern:  /subnivell/confirmar
    defaults: { _controller: "PrincipalBundle:AdminGuia:subnivellConfirmar" }
    requirements: { _method: post }        

guia_editar:
    pattern:  /{id}/editar
    defaults: { _controller: "PrincipalBundle:AdminGuia:editar" }
    
guia_actualitzar:
    pattern:  /{id}/editar/actualitzar
    defaults: { _controller: "PrincipalBundle:AdminGuia:actualitzar" }
    requirements: { _method: post }        
    
guia_eliminar:
    pattern:  /{id}/eliminar
    defaults: { _controller: "PrincipalBundle:Noticies:eliminar" }
    
guia_confirmar:
    pattern:  /{id}/editar/confirm
    defaults: { _controller: "PrincipalBundle:AdminGuia:confirm" }
    requirements: { _method: post }            
