noticies:
    pattern:  /
    defaults: { _controller: "PrincipalBundle:Noticies:index" }

noticies_show:
    pattern:  /{id}/show
    defaults: { _controller: "PrincipalBundle:Noticies:show" }

noticies_new:
    pattern:  /new
    defaults: { _controller: "PrincipalBundle:Noticies:new" }

noticies_create:
    pattern:  /create
    defaults: { _controller: "PrincipalBundle:Noticies:create" }
    requirements: { _method: post }

noticies_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "PrincipalBundle:Noticies:edit" }

noticies_update:
    pattern:  /{id}/update
    defaults: { _controller: "PrincipalBundle:Noticies:update" }
    requirements: { _method: post }

noticies_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "PrincipalBundle:Noticies:delete" }
    requirements: { _method: post }
