admin_usuaris:
    pattern:  /
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:usuaris" }
    
usuaris_crear:
    pattern:  /crear
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:crear" }
    
usuaris_crear_confirmar:
    pattern:  /confirmar/crear
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:crearConfirmar" }
    requirements: { _method: post }
    
usuaris_editar:
    pattern:  /{usuari}/editar
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:editar" }
    
usuaris_editar_confirmar:
    pattern:  /editar/confirmar
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:editarConfirmar" }
    requirements: { _method: post }    
    
usuaris_eliminar:
    pattern:  /{usuari}/eliminar
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:eliminar" }    

usuaris_eliminar_confirmar:
    pattern:  /eliminar/confirmar
    defaults: { _controller: "PrincipalBundle:AdminUsuaris:eliminarConfirmar" }
    requirements: { _method: post }    
    
